//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.8.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, ICompanyInfo, IContactForm, IContactSection, IFooter, IHeader, ISlider
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("button")]
		public string Button => this.Value<string>("button");

		///<summary>
		/// Description Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("descriptionIntro")]
		public string DescriptionIntro => this.Value<string>("descriptionIntro");

		///<summary>
		/// Pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("pages")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.PagePreviewControl> Pages => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.PagePreviewControl>>("pages");

		///<summary>
		/// Title Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("titleIntro")]
		public string TitleIntro => this.Value<string>("titleIntro");

		///<summary>
		/// Url Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("urlAddress")]
		public string UrlAddress => this.Value<string>("urlAddress");

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("address")]
		public string Address => global::Umbraco.Web.PublishedModels.CompanyInfo.GetAddress(this);

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("email")]
		public string Email => global::Umbraco.Web.PublishedModels.CompanyInfo.GetEmail(this);

		///<summary>
		/// Phone Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber => global::Umbraco.Web.PublishedModels.CompanyInfo.GetPhoneNumber(this);

		///<summary>
		/// Social Media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("socialMedia")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> SocialMedia => global::Umbraco.Web.PublishedModels.CompanyInfo.GetSocialMedia(this);

		///<summary>
		/// Sub Title Contact Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("subTitleContactForm")]
		public string SubTitleContactForm => global::Umbraco.Web.PublishedModels.ContactForm.GetSubTitleContactForm(this);

		///<summary>
		/// Title Contact Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("titleContactForm")]
		public string TitleContactForm => global::Umbraco.Web.PublishedModels.ContactForm.GetTitleContactForm(this);

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("yourEmail")]
		public string YourEmail => global::Umbraco.Web.PublishedModels.ContactForm.GetYourEmail(this);

		///<summary>
		/// Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("yourMessage")]
		public string YourMessage => global::Umbraco.Web.PublishedModels.ContactForm.GetYourMessage(this);

		///<summary>
		/// Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("yourName")]
		public string YourName => global::Umbraco.Web.PublishedModels.ContactForm.GetYourName(this);

		///<summary>
		/// Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("yourPhone")]
		public string YourPhone => global::Umbraco.Web.PublishedModels.ContactForm.GetYourPhone(this);

		///<summary>
		/// Description Contact Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("descriptionContactSection")]
		public string DescriptionContactSection => global::Umbraco.Web.PublishedModels.ContactSection.GetDescriptionContactSection(this);

		///<summary>
		/// Image Contact Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("imageContactSection")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent ImageContactSection => global::Umbraco.Web.PublishedModels.ContactSection.GetImageContactSection(this);

		///<summary>
		/// Sub Title Contact Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("subTitleContactSection")]
		public string SubTitleContactSection => global::Umbraco.Web.PublishedModels.ContactSection.GetSubTitleContactSection(this);

		///<summary>
		/// Title Contact Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("titleContactSection")]
		public string TitleContactSection => global::Umbraco.Web.PublishedModels.ContactSection.GetTitleContactSection(this);

		///<summary>
		/// Group Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("groupMenu")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.GroupLinks> GroupMenu => global::Umbraco.Web.PublishedModels.Footer.GetGroupMenu(this);

		///<summary>
		/// Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("logo")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Logo => global::Umbraco.Web.PublishedModels.Header.GetLogo(this);

		///<summary>
		/// Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("menu")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> Menu => global::Umbraco.Web.PublishedModels.Header.GetMenu(this);

		///<summary>
		/// Slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.8.0")]
		[ImplementPropertyType("sliderItems")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SliderItem> SliderItems => global::Umbraco.Web.PublishedModels.Slider.GetSliderItems(this);
	}
}
